name: House History Web Build and Push

on:
  push:
    branches:
      - main

env:
    DIR: Web

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: adamfallon.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        allow-no-subscriptions: true

    - name: Build and Push
      working-directory: ${{env.DIR}}
      run: |
        docker build . -t adamfallon.azurecr.io/househistory/househistory-web:${{ github.sha }}
        docker push adamfallon.azurecr.io/househistory/househistory-web:${{ github.sha }}
        docker build . -t adamfallon.azurecr.io/househistory/househistory-api:${{ github.sha }}
        docker push adamfallon.azurecr.io/househistory/househistory-api:${{ github.sha }}
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'househistoryapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: |-
          'adamfallon.azurecr.io/househistory/househistory-web:${{ github.sha }}'
          'adamfallon.azurecr.io/househistory/househistory-api:${{ github.sha }}'
        configuration-file: prod.yml
