name: House History Web Build and Push

on:
  pull_request:
    branches:
      - main
    types: [closed]

env:
    DIR: Web

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: adamfallon.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build and Push
      working-directory: ${{env.DIR}}
      run: |
        docker build . -t adamfallon.azurecr.io/househistory/househistory-web:${{ github.sha }}
        docker push adamfallon.azurecr.io/househistory/househistory-web:${{ github.sha }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'househistoryapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_WEB }}
        images: 'adamfallon.azurecr.io/househistory/househistory-web:${{ github.sha }}'